---
.template: &template
  except:
    - deploy@ftp-team/dak

test buster:
  <<: *template
  image: debian:buster
  parallel: 5
  script: debian/run-ci --with-coverage
  artifacts:
    expire_in: 1 day
    paths:
      - coverage
      - output

tests buster python3:
  <<: *template
  image: debian:buster
  script: debian/run-ci --python3
  artifacts:
    paths:
      - coverage
      - output

flake8:
  <<: *template
  image: debian:9
  script:
    - apt-get update
    - apt-get install -y python-flake8
    - python -mflake8

get coverage:
  image: debian:buster
  stage: coverage
  dependencies:
    - test buster
  script:
    - debian/run-coverage
  artifacts:
    paths:
      - coverage
      - logs

pages:
  image: debian:9
  script:
    - apt-get update
    - apt-get install -y python-epydoc
    - mkdir -p public/epydoc
    - epydoc -q --html --graph all --css white -n DAK -o public/epydoc --include-log --show-imports dak dakweb
    - mv coverage public/coverage
  stage: deploy
  artifacts:
    paths:
      - public
  only:
    - master

stages:
  - test
  - coverage
  - deploy
