#! /bin/sh
# $Id: mkmaintainers,v 1.2 2001-09-26 03:47:15 troup Exp $

echo
echo -n 'Creating Maintainers index ... '

set -e
. $SCRIPTVARS
cd $masterdir

nonusmaint="$masterdir/Maintainers_Versions-non-US"


if wget -q -O Maintainers_Versions-non-US.gz http://non-us.debian.org/indices-non-US/Maintainers_Versions.gz; then
	rm -f $nonusmaint
	gunzip -c ${nonusmaint}.gz > $nonusmaint
	rm -f ${nonusmaint}.gz
fi

cd $indices
$masterdir/charisma $nonusmaint $masterdir/pseudo-packages.maintainers | sed -e "s/~[^  ]*\([   ]\)/\1/"  | awk '{printf "%-20s ", $1; for (i=2; i<=NF; i++) printf "%s ", $i; printf "\n";}' > .new-maintainers

set +e
cmp .new-maintainers Maintainers >/dev/null
rc=$?
set -e
if [ $rc = 1 ] || [ ! -f Maintainers ] ; then
	echo -n "installing Maintainers ... "
	mv -f .new-maintainers Maintainers
	gzip -9v <Maintainers >.new-maintainers.gz
	mv -f .new-maintainers.gz Maintainers.gz
elif [ $rc = 0 ] ; then
	echo '(same as before)'
	rm -f .new-maintainers
else
	echo cmp returned $rc
	false
fi
