#!/usr/bin/env python

# Sanity check the database
# Copyright (C) 2000, 2001, 2002  James Troup <james@nocrew.org>
# $Id: tea,v 1.22 2003-01-02 18:14:02 troup Exp $

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

################################################################################

#   And, lo, a great and menacing voice rose from the depths, and with
#   great wrath and vehemence it's voice boomed across the
#   land... ``hehehehehehe... that *tickles*''
#                                                       -- aj on IRC

################################################################################

import pg, sys, os, stat, time
import utils, db_access
import apt_pkg, apt_inst;

################################################################################

Cnf = None;
projectB = None;
db_files = {};
waste = 0.0;
excluded = {};
current_file = None;
future_files = {};
current_time = time.time();

################################################################################

def usage(exit_code=0):
    print """Usage: tea MODE
Run various sanity checks of the archive and/or database.

  -h, --help                show this help and exit.

The following MODEs are available:

  md5sums            - validate the md5sums stored in the database
  files              - check files in the database against what's in the archive
  dsc-syntax         - validate the syntax of .dsc files in the archive
  missing-overrides  - check for missing overrides
  source-in-one-dir  - ensure the source for each package is in one directory
  timestamps         - check for future timestamps in .deb's
  tar-gz-in-dsc      - ensure each .dsc lists a .tar.gz file
"""
    sys.exit(exit_code)

################################################################################

def process_dir (unused, dirname, filenames):
    global waste, db_files, excluded;

    if dirname.find('/disks-') != -1 or dirname.find('upgrade-') != -1:
        return;
    # hack; can't handle .changes files
    if dirname.find('proposed-updates') != -1:
        return;
    for name in filenames:
        filename = os.path.abspath(dirname+'/'+name);
        filename = filename.replace('potato-proposed-updates', 'proposed-updates');
        if os.path.isfile(filename) and not os.path.islink(filename) and not db_files.has_key(filename) and not excluded.has_key(filename):
            waste += os.stat(filename)[stat.ST_SIZE];
            print filename

################################################################################

def check_files():
    global db_files;

    print "Building list of database files...";
    q = projectB.query("SELECT l.path, f.filename FROM files f, location l WHERE f.location = l.id")
    ql = q.getresult();

    db_files.clear();
    for i in ql:
	filename = os.path.abspath(i[0] + i[1]);
        db_files[filename] = "";
        if os.access(filename, os.R_OK) == 0:
            utils.warn("'%s' doesn't exist." % (filename));

    file = utils.open_file(Cnf["Dir::Override"]+'override.unreferenced');
    for filename in file.readlines():
        filename = filename[:-1];
        excluded[filename] = "";

    print "Checking against existent files...";

    os.path.walk(Cnf["Dir::Root"]+'dists/', process_dir, None);

    print
    print "%s wasted..." % (utils.size_type(waste));

################################################################################

def check_dscs():
    count = 0;
    suite = 'unstable';
    for component in Cnf.SubTree("Component").List():
        if component == "mixed":
            continue;
        component = component.lower();
        list_filename = '%s%s_%s_source.list' % (Cnf["Dir::Lists"], suite, component);
        list_file = utils.open_file(list_filename);
        for line in list_file.readlines():
            file = line[:-1];
            try:
                utils.parse_changes(file, dsc_whitespace_rules=1);
            except utils.invalid_dsc_format_exc, line:
                utils.warn("syntax error in .dsc file '%s', line %s." % (file, line));
                count += 1;

    if count:
        utils.warn("Found %s invalid .dsc files." % (count));

################################################################################

def check_override():
    for suite in [ "stable", "unstable" ]:
        print suite
        print "-------------"
        print
        suite_id = db_access.get_suite_id(suite);
        q = projectB.query("""
SELECT DISTINCT b.package FROM binaries b, bin_associations ba
 WHERE b.id = ba.bin AND ba.suite = %s AND NOT EXISTS
       (SELECT * FROM override o WHERE o.suite = %s AND o.package = b.package)"""
                           % (suite_id, suite_id));
        print q
        q = projectB.query("""
SELECT DISTINCT s.source FROM source s, src_associations sa
  WHERE s.id = sa.source AND sa.suite = %s AND NOT EXISTS
       (SELECT * FROM override o WHERE o.suite = %s and o.package = s.source)"""
                           % (suite_id, suite_id));
        print q

################################################################################

# Ensure that the source files for any given package is all in one
# directory so that 'apt-get source' works...

def check_source_in_one_dir():
    # Not the most enterprising method, but hey...
    broken_count = 0;
    q = projectB.query("SELECT id FROM source;");
    for i in q.getresult():
        source_id = i[0];
        q2 = projectB.query("""
SELECT l.path, f.filename FROM files f, dsc_files df, location l WHERE df.source = %s AND f.id = df.file AND l.id = f.location"""
                            % (source_id));
        first_path = "";
        first_filename = "";
        broken = 0;
        for j in q2.getresult():
            filename = j[0] + j[1];
            path = os.path.dirname(filename);
            if first_path == "":
                first_path = path;
                first_filename = filename;
            elif first_path != path:
                symlink = path + '/' + os.path.basename(first_filename);
                if not os.path.exists(symlink):
                    broken = 1;
                    print "WOAH, we got a live one here... %s [%s] {%s}" % (filename, source_id, symlink);
        if broken:
            broken_count += 1;
    print "Found %d source packages where the source is not all in one directory." % (broken_count);

################################################################################

def check_md5sums():
    print "Getting file information from database...";
    q = projectB.query("SELECT l.path, f.filename, f.md5sum, f.size FROM files f, location l WHERE f.location = l.id")
    ql = q.getresult();

    print "Checking file md5sums & sizes...";
    for i in ql:
	filename = os.path.abspath(i[0] + i[1]);
        db_md5sum = i[2];
        db_size = int(i[3]);
        try:
            file = utils.open_file(filename);
        except:
            utils.warn("can't open '%s'." % (filename));
            continue;
        md5sum = apt_pkg.md5sum(file);
        size = os.stat(filename)[stat.ST_SIZE];
        if md5sum != db_md5sum:
            utils.warn("**WARNING** md5sum mismatch for '%s' ('%s' [current] vs. '%s' [db])." % (filename, md5sum, db_md5sum));
        if size != db_size:
            utils.warn("**WARNING** size mismatch for '%s' ('%s' [current] vs. '%s' [db])." % (filename, size, db_size));

    print "Done."

################################################################################
#
# Check all files for timestamps in the future; common from hardware
# (e.g. alpha) which have far-future dates as their default dates.



def Ent(Kind,Name,Link,Mode,UID,GID,Size,MTime,Major,Minor):
    global future_files;

    if MTime > current_time:
        future_files[current_file] = MTime;
        print "%s: %s '%s','%s',%u,%u,%u,%u,%u,%u,%u" % (current_file, Kind,Name,Link,Mode,UID,GID,Size, MTime, Major, Minor);

def check_timestamps():
    global current_file;

    q = projectB.query("SELECT l.path, f.filename FROM files f, location l WHERE f.location = l.id AND f.filename ~ '.deb$'")
    ql = q.getresult();
    db_files.clear();
    count = 0;
    for i in ql:
	filename = os.path.abspath(i[0] + i[1]);
        if os.access(filename, os.R_OK):
            file = utils.open_file(filename);
            current_file = filename;
            sys.stderr.write("Processing %s.\n" % (filename));
            apt_inst.debExtract(file,Ent,"control.tar.gz");
            file.seek(0);
            apt_inst.debExtract(file,Ent,"data.tar.gz");
            count += 1;
    print "Checked %d files (out of %d)." % (count, len(db_files.keys()));

################################################################################

def check_missing_tar_gz_in_dsc():
    count = 0;

    print "Building list of database files...";
    q = projectB.query("SELECT l.path, f.filename FROM files f, location l WHERE f.location = l.id AND f.filename ~ '.dsc$'");
    ql = q.getresult();
    if ql:
        print "Checking %d files..." % len(ql);
    else:
        print "No files to check."
    for i in ql:
        filename = os.path.abspath(i[0] + i[1]);
        try:
            # NB: don't enforce .dsc syntax
            dsc = utils.parse_changes(filename);
        except:
            utils.fubar("error parsing .dsc file '%s'." % (filename));
        dsc_files = utils.build_file_list(dsc, is_a_dsc=1);
        has_tar = 0;
        for file in dsc_files.keys():
            m = utils.re_issource.match(file);
            if not m:
                utils.fubar("%s not recognised as source." % (file));
            type = m.group(3);
            if type == "orig.tar.gz" or type == "tar.gz":
                has_tar = 1;
        if not has_tar:
            utils.warn("%s has no .tar.gz in the .dsc file." % (file));
            count += 1;

    if count:
        utils.warn("Found %s invalid .dsc files." % (count));

################################################################################

def main ():
    global Cnf, projectB, db_files, waste, excluded;

    Cnf = utils.get_conf();
    Arguments = [('h',"help","Tea::Options::Help")];
    for i in [ "help" ]:
	if not Cnf.has_key("Tea::Options::%s" % (i)):
	    Cnf["Tea::Options::%s" % (i)] = "";

    args = apt_pkg.ParseCommandLine(Cnf, Arguments, sys.argv);

    Options = Cnf.SubTree("Tea::Options")
    if Options["Help"]:
	usage();

    if len(args) < 1:
        utils.warn("tea requires at least one argument");
        usage(1);
    elif len(args) > 1:
        utils.warn("tea accepts only one argument");
        usage(1);
    mode = args[0].lower();

    projectB = pg.connect(Cnf["DB::Name"], Cnf["DB::Host"], int(Cnf["DB::Port"]));
    db_access.init(Cnf, projectB);

    if mode == "md5sums":
        check_md5sums();
    elif mode == "files":
        check_files();
    elif mode == "dsc-syntax":
        check_dscs();
    elif mode == "missing-overrides":
        check_override();
    elif mode == "source-in-one-dir":
        check_source_in_one_dir();
    elif mode == "timestamps":
        check_timestamps();
    elif mode == "tar-gz-in-dsc":
        check_missing_tar_gz_in_dsc();
    else:
        utils.warn("unknown mode '%s'" % (mode));
        usage(1);

################################################################################

if __name__ == '__main__':
    main();

