#!/bin/sh
#
# Fetches up to date copy of REAME.non-US for pandora
# Michael Beattie <mjb@debian.org>

. vars-non-US

cd $ftpdir

echo Updating non-US version of README.non-US
wget -t1 -T20 -q -N http://ftp-master.debian.org/README.non-US || \
  echo "Some error occured..."

