# -*- make -*-
BASE=..
SUBDIR=doc

# Bring in the default rules
include ../buildlib/defaults.mak

# SGML Documents
SOURCE = filelist.sgml
include $(DEBIANDOC_H)

# Man pages
SOURCE = dsync-flist.1
include $(YODL_MANPAGE_H)
