#!/bin/sh -ue

# Tarball to read, compressed with gzip
INPUT="${1:?"Usage: $0 filename"}"

# Regular expression used to validate tag lines
CHECKRE='^[a-z0-9A-Z.+-]+[[:space:]]+Task[[:space:]]+[a-z0-9:. ,{}+-]+$'

# This must end with /
TARGET=/srv/ftp.debian.org/scripts/external-overrides/

# Read the main directory from the tarball
DIR="`tar ztf \"$INPUT\" | tac | tail -n 1`"

# Create temporary files where to store the validated data
umask 002
OUTMAIN="`mktemp \"$TARGET\"task.new.XXXXXX`"

# If we fail somewhere, cleanup the temporary files
cleanup() {
        rm -f "$OUTMAIN"
}
trap cleanup EXIT

# Extract the data into the temporary files
tar -O -zxf "$INPUT" "$DIR"task | grep -E "$CHECKRE" > "$OUTMAIN"

# Move the data to the final location
mv "$OUTMAIN"           "$TARGET"task

chmod 644 "$TARGET"task

(cd $TARGET && ./mk-extra-overrides.sh)

trap - EXIT

exit 0
