#!/bin/bash
#
# Copyright (C) 2019, Ansgar Burchardt <ansgar@debian.org>
# License: GPL-2+
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

set -eu
set -o pipefail

if [ $# -le 1 ]; then
    echo >&2 "usage: $0 <files...>"
    echo >&2
    echo >&2 "merge multiple (cleartext or detached) signatures into one"
    exit 0
fi

sed '/^-----BEGIN PGP SIGNATURE-----/ Q' "${1}"

sed -sn '/^-----BEGIN PGP SIGNATURE-----/,$ p' "${@}" |
    gpg --dearmor - |
    gpg --enarmor - |
    sed 's/^-----\(.*\) PGP ARMORED FILE-----/-----\1 PGP SIGNATURE-----/; /^Comment:/ d'
