#!/bin/sh
# Update the md5sums file

set -e
. $SCRIPTVARS

dsynclist=$dbdir/dsync.list
md5list=$indices/md5sums

echo -n "Creating md5 / dsync index file ... "

cd "$ftpdir"
${bindir}/dsync-flist -q generate $dsynclist --exclude $dsynclist --md5
${bindir}/dsync-flist -q md5sums $dsynclist | gzip -9n > ${md5list}.gz
${bindir}/dsync-flist -q link-dups $dsynclist || true
