#!/bin/sh
# Update the md5sums file
# $Id: mkchecksums,v 1.2 2000-12-20 08:15:35 troup Exp $

set -e
. $SCRIPTVARS

dsynclist=$dbdir/dsync.list
md5list=$indices/md5sums

echo -n "Creating md5 / dsync index file ... "

cd "$ftpdir"
dsync-flist -q generate $dsynclist --exclude $dsynclist --md5
dsync-flist -q md5sums $dsynclist | gzip -9n > ${md5list}.gz
dsync-flist -q link-dups $dsynclist || true
