#! /bin/sh

echo
echo -n 'Creating Maintainers index ... '

set -e
. $SCRIPTVARS
cd $base/misc/

cd $indices
dak make-maintainers $configdir/pseudo-packages.maintainers | sed -e "s/~[^  ]*\([   ]\)/\1/"  | awk '{printf "%-20s ", $1; for (i=2; i<=NF; i++) printf "%s ", $i; printf "\n";}' > .new-maintainers

set +e
cmp .new-maintainers Maintainers >/dev/null
rc=$?
set -e
if [ $rc = 1 ] || [ ! -f Maintainers ] ; then
	echo -n "installing Maintainers ... "
	mv -f .new-maintainers Maintainers
	gzip -9v <Maintainers >.new-maintainers.gz
	mv -f .new-maintainers.gz Maintainers.gz
elif [ $rc = 0 ] ; then
	echo '(same as before)'
	rm -f .new-maintainers
else
	echo cmp returned $rc
	false
fi
