#!/bin/bash
#
# Very Very hackish script...  dont laugh.
# Michael Beattie <mjb@debian.org>

set -e

export SCRIPTVARS=/srv/ftp-master.debian.org/dak/config/debian/vars
. $SCRIPTVARS

prog=$scriptdir/mirrorlist/mirror_list.pl
masterlist=$scriptdir/mirrorlist/Mirrors.masterlist

test ! -f $HOME/.cvspass && touch $HOME/.cvspass

grep -q "anonscm.debian.org:/cvs/webwml" ~/.cvspass || \
	echo ":pserver:anonymous@anonscm.debian.org:/cvs/webwml A" >> $HOME/.cvspass

cd $(dirname $masterlist)
cvs update

if [ ! -f $ftpdir/README.mirrors.html -o $masterlist -nt $ftpdir/README.mirrors.html ] ; then
	rm -f $ftpdir/README.mirrors.html $ftpdir/README.mirrors.txt
	$prog -m $masterlist -t html > $ftpdir/README.mirrors.html
	$prog -m $masterlist -t text > $ftpdir/README.mirrors.txt
	echo Updated archive version of mirrors file
fi
