#!/bin/sh

set -e
set -u

echo "Creating core queues"

QUEUEBASE="${DAKBASE}/queue"

psql << EOF
COPY policy_queue (queue_name, path, perms, change_perms,
                   generate_metadata, stay_of_execution, send_to_build_queues) FROM stdin;
unchecked	${QUEUEBASE}/unchecked	0660	0660	FALSE	86400	FALSE
new	${QUEUEBASE}/new	0660	0660	FALSE	86400	FALSE
newstage	${QUEUEBASE}/newstage	0660	0660	FALSE	86400	FALSE
byhand	${QUEUEBASE}/byhand	0660	0660	FALSE	86400	FALSE
\.
EOF
