#!/bin/sh

echo "Creating default sections"

set -e
set -u

SECTIONS="admin
cli-mono
comm
database
debian-installer
debug
devel
doc
editors
education
electronics
embedded
fonts
games
gnome
gnu-r
gnustep
graphics
hamradio
haskell
httpd
interpreters
introspection
java
kde
kernel
libdevel
libs
lisp
localization
mail
math
metapackages
misc
net
news
ocaml
oldlibs
otherosfs
perl
php
python
ruby
science
shells
sound
tasks
tex
text
utils
vcs
video
web
x11
xfce
zope"

for prefix in "" "contrib/" "non-free/"; do
    for section in ${SECTIONS}; do
        psql -c "INSERT INTO section (section) VALUES ('$prefix$section')" >/dev/null
    done
done
