#! /bin/bash
#
# © 2017 Ansgar Burchardt <ansgar@debian.org>
# License: GPL-2+
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

set -e
set -u

. "$(dirname "${BASH_SOURCE}")/runner-lib"

TESTS="$@"

if [ -z "$TESTS" ]
then
	TESTS="${DAK_ROOT}/integration-tests/tests/[0-9]*[^~] \
		${DAK_ROOT}/tests/run-dbtests"
fi

for t in $TESTS; do
  echo "=== Running ${t##*/}"
  set +e
  run-script-with-pg "${t}"
  res=$?
  set -e
  if [ $res != 0 ]
  then
	  echo test $t failed
	  exit 1
  fi
done
