#!/bin/bash

set -e

# list of architectures taken from
# http://buildd.debian.org/stats/

# For debugging, you can override the path using
# the WB_DB_DIR enviroment variable
if [ -z "$WB_DB_DIR" ]
then
	WB_DB_DIR=/srv/ftp.debian.org/scripts/nfu
fi

cd $WB_DB_DIR || { echo "Failed to cd to $WB_DB_DIR" ; exit 1 ;}

for arch in alpha amd64 arm armel hppa i386 ia64 mips mipsel powerpc s390 sparc
do
	rm -f $arch-all.txt
	echo "Getting $arch-all.txt"
	wget -q http://buildd.debian.org/stats/$arch-all.txt
done
